"use client";
import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "fr" | "en" | "ar";
export type Currency = "DZD" | "USD" | "EUR";

const RATES: Record<Currency, number> = {
  DZD: 1,
  USD: 1 / 135,
  EUR: 1 / 145,
};

const SYMBOLS: Record<Currency, string> = {
  DZD: "DA",
  USD: "$",
  EUR: "€",
};

type AppCtx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  currency: Currency;
  setCurrency: (c: Currency) => void;
  t: (key: string) => string;
  fmt: (amountInDZD: number) => string;
};

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    dashboard: "Tableau de bord",
    products: "Produits",
    orders: "Commandes",
    customers: "Clients",
    finance: "Finance",
    reports: "Rapports",
    settings: "Paramètres",
    help: "Aide",
    main_menu: "Menu Principal",
    support: "Support",
    welcome: "Bon retour, Admin ZAIMI 👋",
    search: "Rechercher...",
    new_products: "Nouveaux Produits",
    available_stock: "Stock Disponible",
    new_orders: "Nouvelles Commandes",
    new_customers: "Nouveaux Clients",
    vs_last_month: "vs mois dernier",
    profit_by_category: "Profit par Catégorie",
    annual_breakdown: "Répartition annuelle",
    total_revenue: "Revenu Total",
    order_summary: "Résumé des Commandes",
    full_year: "Année complète 2025",
    stock_level: "Niveau de Stock",
    upcoming_restocks: "Réapprovisionnements",
    traffic_sources: "Sources de Trafic",
    last_30_days: "30 derniers jours",
    recent_activity: "Activité Récente",
    product: "Produit",
    sku: "SKU",
    qty: "Qté",
    status: "Statut",
    healthy: "Bon",
    low: "Bas",
    critical: "Critique",
    add_product: "Ajouter Produit",
    add_customer: "Ajouter Client",
    new_order: "Nouvelle Commande",
    export_pdf: "Exporter PDF",
    filter: "Filtrer",
    edit: "Modifier",
    total_products: "produits au total",
    registered_customers: "clients enregistrés",
    manage_orders: "Gérer et suivre toutes les commandes",
    order_id: "N° Commande",
    customer: "Client",
    total: "Total",
    date: "Date",
    delivered: "Livré",
    processing: "En cours",
    pending: "En attente",
    cancelled: "Annulé",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    orders_col: "Commandes",
    total_spent: "Total Dépensé",
    active: "Actif",
    vip: "VIP",
    new: "Nouveau",
    inactive: "Inactif",
    finance_title: "Finance",
    finance_sub: "Vue financière — 2025",
    total_revenue_card: "Revenu Total",
    total_expenses: "Dépenses Totales",
    net_profit: "Bénéfice Net",
    income_vs_expenses: "Revenus vs Dépenses",
    recent_transactions: "Transactions Récentes",
    reports_title: "Rapports",
    reports_sub: "Analyse & Intelligence commerciale",
    sales_trend: "Tendance des Ventes — S1 2025",
    units_sold: "Unités Vendues par Produit",
    top_products: "Top Produits par Revenu",
    rank: "Rang",
    units: "Unités",
    revenue: "Revenu",
    share: "Part",
    categories: { electronics: "Électronique", accessories: "Accessoires", networking: "Réseau", software: "Logiciel" } as any,
    direct: "Direct",
    referral: "Référence",
    organic: "Organique",
    social: "Réseaux Sociaux",
    email_traffic: "Email",
    ytd: "Cumul 2025",
  },
  en: {
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    customers: "Customers",
    finance: "Finance",
    reports: "Reports",
    settings: "Settings",
    help: "Help",
    main_menu: "Main Menu",
    support: "Support",
    welcome: "Welcome back, Admin ZAIMI 👋",
    search: "Search anything...",
    new_products: "New Products",
    available_stock: "Available Stock",
    new_orders: "New Orders",
    new_customers: "New Customers",
    vs_last_month: "vs last month",
    profit_by_category: "Profit by Category",
    annual_breakdown: "Annual breakdown",
    total_revenue: "Total Revenue",
    order_summary: "Order Summary",
    full_year: "Full year 2025",
    stock_level: "Stock Level",
    upcoming_restocks: "Upcoming Restocks",
    traffic_sources: "Traffic Sources",
    last_30_days: "Last 30 days",
    recent_activity: "Recent Activity",
    product: "Product",
    sku: "SKU",
    qty: "Qty",
    status: "Status",
    healthy: "Healthy",
    low: "Low",
    critical: "Critical",
    add_product: "Add Product",
    add_customer: "Add Customer",
    new_order: "New Order",
    export_pdf: "Export PDF",
    filter: "Filter",
    edit: "Edit",
    total_products: "total products",
    registered_customers: "registered customers",
    manage_orders: "Manage and track all orders",
    order_id: "Order ID",
    customer: "Customer",
    total: "Total",
    date: "Date",
    delivered: "Delivered",
    processing: "Processing",
    pending: "Pending",
    cancelled: "Cancelled",
    name: "Name",
    email: "Email",
    phone: "Phone",
    orders_col: "Orders",
    total_spent: "Total Spent",
    active: "Active",
    vip: "VIP",
    new: "New",
    inactive: "Inactive",
    finance_title: "Finance",
    finance_sub: "Financial overview — 2025",
    total_revenue_card: "Total Revenue",
    total_expenses: "Total Expenses",
    net_profit: "Net Profit",
    income_vs_expenses: "Income vs Expenses",
    recent_transactions: "Recent Transactions",
    reports_title: "Reports",
    reports_sub: "Business intelligence & analytics",
    sales_trend: "Sales Trend — H1 2025",
    units_sold: "Units Sold by Product",
    top_products: "Top Products by Revenue",
    rank: "Rank",
    units: "Units",
    revenue: "Revenue",
    share: "Share",
    direct: "Direct",
    referral: "Referral",
    organic: "Organic",
    social: "Social",
    email_traffic: "Email",
    ytd: "YTD 2025",
  },
  ar: {
    dashboard: "لوحة التحكم",
    products: "المنتجات",
    orders: "الطلبات",
    customers: "العملاء",
    finance: "المالية",
    reports: "التقارير",
    settings: "الإعدادات",
    help: "المساعدة",
    main_menu: "القائمة الرئيسية",
    support: "الدعم",
    welcome: "مرحباً بك، المدير زايمي 👋",
    search: "البحث...",
    new_products: "منتجات جديدة",
    available_stock: "المخزون المتاح",
    new_orders: "طلبات جديدة",
    new_customers: "عملاء جدد",
    vs_last_month: "مقارنة بالشهر الماضي",
    profit_by_category: "الربح حسب الفئة",
    annual_breakdown: "التوزيع السنوي",
    total_revenue: "إجمالي الإيرادات",
    order_summary: "ملخص الطلبات",
    full_year: "السنة الكاملة 2025",
    stock_level: "مستوى المخزون",
    upcoming_restocks: "إعادة التخزين القادمة",
    traffic_sources: "مصادر الزيارات",
    last_30_days: "آخر 30 يوم",
    recent_activity: "النشاط الأخير",
    product: "المنتج",
    sku: "الرمز",
    qty: "الكمية",
    status: "الحالة",
    healthy: "جيد",
    low: "منخفض",
    critical: "حرج",
    add_product: "إضافة منتج",
    add_customer: "إضافة عميل",
    new_order: "طلب جديد",
    export_pdf: "تصدير PDF",
    filter: "تصفية",
    edit: "تعديل",
    total_products: "منتج إجمالاً",
    registered_customers: "عميل مسجل",
    manage_orders: "إدارة وتتبع جميع الطلبات",
    order_id: "رقم الطلب",
    customer: "العميل",
    total: "الإجمالي",
    date: "التاريخ",
    delivered: "مُسلَّم",
    processing: "قيد المعالجة",
    pending: "معلق",
    cancelled: "ملغي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    orders_col: "الطلبات",
    total_spent: "إجمالي الإنفاق",
    active: "نشط",
    vip: "VIP",
    new: "جديد",
    inactive: "غير نشط",
    finance_title: "المالية",
    finance_sub: "نظرة مالية — 2025",
    total_revenue_card: "إجمالي الإيرادات",
    total_expenses: "إجمالي المصروفات",
    net_profit: "صافي الربح",
    income_vs_expenses: "الإيرادات مقابل المصروفات",
    recent_transactions: "المعاملات الأخيرة",
    reports_title: "التقارير",
    reports_sub: "ذكاء الأعمال والتحليلات",
    sales_trend: "اتجاه المبيعات — النصف الأول 2025",
    units_sold: "الوحدات المباعة حسب المنتج",
    top_products: "أفضل المنتجات حسب الإيرادات",
    rank: "الترتيب",
    units: "الوحدات",
    revenue: "الإيرادات",
    share: "الحصة",
    direct: "مباشر",
    referral: "إحالة",
    organic: "عضوي",
    social: "التواصل الاجتماعي",
    email_traffic: "بريد إلكتروني",
    ytd: "منذ بداية العام 2025",
  },
};

const AppContext = createContext<AppCtx>({} as AppCtx);

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("fr");
  const [currency, setCurrency] = useState<Currency>("DZD");

  const t = (key: string) => translations[lang][key] ?? key;

  const fmt = (amountInDZD: number) => {
    const converted = amountInDZD * RATES[currency];
    const symbol = SYMBOLS[currency];
    if (currency === "DZD") {
      return `${Math.round(converted).toLocaleString("fr-DZ")} ${symbol}`;
    }
    return `${symbol}${converted.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
  };

  return (
    <AppContext.Provider value={{ lang, setLang, currency, setCurrency, t, fmt }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"} style={{ fontFamily: lang === "ar" ? "'Segoe UI', Tahoma, Arial, sans-serif" : "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
        {children}
      </div>
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);
